version: 2


jobs:
  build:
    docker:
      - image: "osrf/ros:foxy-desktop"
    steps:
      - checkout
      - run:
          name: local_setup
          command: 
            source /opt/ros/foxy/local_setup.bash
            colcon build
