version: 2


jobs:
  build:
    docker:
      - image: "osrf/ros:foxy-desktop"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  # default - false
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing tzdata
          command: 'DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get install -y tzdata'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: source /opt/ros/foxy/setup.sh
          command: 'source /opt/ros/foxy/setup.sh'
      - run:
          name: Build
          command: |
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            cd ..
            colcon build
